### ISSUE TITLE
Implement mset method

### ISSUE THREAD

**Issue by michaeldzjap** [node-cache/node-cache#124]
This would be a nice addition. Especially since `mget` already exists.

**Comment by erdii** [comment]
We don't see this as needed, but we also would accept a pr with `mset`-functionality if it includes tests.

**Comment by michaeldzjap** [comment]
@erdii Ok, I understand. I would be happy to submit a PR if I had the time, but I have too much on my plate already at the moment. So I will just close this for now. Maybe in the future.

**Comment by erdii** [comment]
I'll reopen this and add a [PR NEEDED] label

**Comment by sujeshthekkepatt** [comment]
Hai I would like to give a PR. How are you guys planning to implement this? Currently set method accepts 3 params. So what would be the 'mset' signature look like? 
`mset( [ {key, val, [ttl],}] )`

It will accept an array of objects in which the object will have the following structure ,
` {
key:key,
val:value,
ttl:ttil
}`.
Is this okay ?

**Comment by erdii** [comment]
Hey @sujeshthekkepatt, nice!!! :)

Some thougts:
* should we check if the cache has space for the full mset operation?
* should mset have some kind of transaction logic? (I would tend to say yes, because what's the point of having an integrated mset over an ordinary for-loop that is implemented by the library consumer)
* I think this boolean return stuff should be completely removed from node-cache

What do you - and possibly others - think?

**Comment by sujeshthekkepatt** [comment]
Hey, @erdii thanks for your reply. Actually I can't find enough docs for researching about mset operation (Any help would be great :) ). Also, how are you proposing to implement the transaction? Do you have any resources that worth a read?

**Comment by erdii** [comment]
Actually I don't have an idea for now. Brainstorming a bit:
* js is single-threaded, so we don't need a locking mechanism
* i think maybe, just validate all objects in `keyValueSet` for valid `key` and `ttl` keys, then set them in a loop

I think this should prevent (almost) all error that can happen in the set loop. That's not a real transaction as we don't have a rollback logic in case something throws in the set loop, but we prevent
* ECACHEFULL errors, as we check for enough space
* errors with invalid key and ttl values

what do you think?

also cc @daluf and @vtii

**Comment by sujeshthekkepatt** [comment]
@erdii  So for clarity, you are saying something like,

1. loop over `keyValueSet` and validate the `key`,`ttl`.
2. For any kind of `error`, we just stop and throw that error. (or We can remove that invalid object from it and continue with rest. If it makes sense :) )
3. Then loop over the valid `keyValueSet` and call the `set` method.
Is this what you meant? Also implementing transaction logic seems little overdoing. Do we really need that? Step 2 can prevent almost any error that can happen in the set loop. To implement rollback logic I think we have to back up existing cache object and replace whenever any error occurs.

**Comment by erdii** [comment]
Yes thats what I mean. :) I also think that full blown transactions would be way over the top here.

I'd tend to reject an mset containing invalid values with the reasoning, that we just throw an error and don't have to return a structure that tells the caller which keys were set and which errored.

**Comment by sujeshthekkepatt** [comment]
Cool. If that is I am happy to work on it. Is there anything else should taken care of? @erdii

**Comment by erdii** [comment]
Please add tests as well :)

**Comment by sujeshthekkepatt** [comment]
Hey any update on the PR @erdii @michaeldzjap

**Comment by daluf** [comment]
Your PR (https://github.com/node-cache/node-cache/pull/142) has been merged to master. Thank you for your contribution.
