### ISSUE TITLE
autoRemove option

### ISSUE THREAD

**Issue by fivemru** [node-cache/node-cache#145]
Hello.
How about the **autoRemove** option?
It would be very convenient to have this option paired with **maxKeys**.
When the limit is reached, and when **autoRemove** is **true**, do not throw an exception and delete the oldest entries.
When **autoRemove** is **false** (default) - throw an exception.
What do you think of it?

**Comment by daluf** [comment]
duplicate #76 
please use https://github.com/isaacs/node-lru-cache
