### ISSUE TITLE
Performance question - 16ms on average for get()

### ISSUE THREAD

**Issue by vinoa-team** [node-cache/node-cache#147]
Hi,

I've started using your plugin and am testing it at present on a few routes.

So far, after a few days of road-testing it, I'm currently getting an average of 18ms for a simple `get('key')`
The server is running Node 8, it's a cloud server hosted by an equivalent of AWS so am not entirely sure of what underlying CU/Memory we're setup up to use. So far we've been pretty happy with the performance, and there is auto scaling. Our app doesn't receive a huge amount of traffic (few hundred API calls per hour roughly) so I don't think we're maxing out the server.

Here is a key we typically store in memory:
```
{ _id: 5c7e533ce75227089bd93bbb,
   texts:
    [ { keywords: [Array],
        language: 'FR',
        title: 'Art',
        description: '' },
      { keywords: [], language: 'EN', title: 'Art', description: '' } ],
   extension: 'jpg',
   fileDate: 2019-03-18T17:38:52.553Z,
   createdAt: 2019-03-05T10:45:16.262Z,
   updatedAt: 2019-03-27T15:35:27.619Z,
   __v: 101,
   isDefault: false,
   defaultPhotos:
    [ { _id: 5c9b95bcd74d5c0f766f99f9, extension: 'jpg' },
      { _id: 5c9b95c7d74d5c0f766f99fa, extension: 'jpg' },
      { _id: 5c9b95ced74d5c0f766f99fb, extension: 'jpg' },
      { _id: 5c9b95d5d74d5c0f766f99fc, extension: 'jpg' },
      { _id: 5c9b95d7d74d5c0f766f99fd, extension: 'jpg' },
      { _id: 5c9b95dad74d5c0f766f99fe, extension: 'jpg' },
      { _id: 5c9b95e1d74d5c0f766f99ff, extension: 'jpg' },
      { _id: 5c9b95e7d74d5c0f766f9a00, extension: 'jpg' },
      { _id: 5c9b95e9d74d5c0f766f9a01, extension: 'jpg' },
      { _id: 5c9b95efd74d5c0f766f9a02, extension: 'jpg' },
      { _id: 5c9b95f7d74d5c0f766f9a03, extension: 'jpg' },
      { _id: 5c9b95fdd74d5c0f766f9a04, extension: 'jpg' },
      { _id: 5c9b9602d74d5c0f766f9a05, extension: 'jpg' },
      { _id: 5c9b960ad74d5c0f766f9a06, extension: 'jpg' },
      { _id: 5c9b960fd74d5c0f766f9a07, extension: 'jpg' },
      { _id: 5c9b9614d74d5c0f766f9a08, extension: 'jpg' },
      { _id: 5c9b9616d74d5c0f766f9a09, extension: 'jpg' },
      { _id: 5c9b961ed74d5c0f766f9a0a, extension: 'jpg' },
      { _id: 5c9b9623d74d5c0f766f9a0b, extension: 'jpg' },
      { _id: 5c9b9628d74d5c0f766f9a0c, extension: 'jpg' },
      { _id: 5c9b962ad74d5c0f766f9a0d, extension: 'jpg' },
      { _id: 5c9b962fd74d5c0f766f9a0e, extension: 'jpg' },
      { _id: 5c9b9635d74d5c0f766f9a0f, extension: 'jpg' },
      { _id: 5c9b963cd74d5c0f766f9a10, extension: 'jpg' },
      { _id: 5c9b9642d74d5c0f766f9a11, extension: 'jpg' },
      { _id: 5c9b964ad74d5c0f766f9a12, extension: 'jpg' },
      { _id: 5c9b9650d74d5c0f766f9a13, extension: 'jpg' },
      { _id: 5c9b9658d74d5c0f766f9a14, extension: 'jpg' },
      { _id: 5c9b965ed74d5c0f766f9a15, extension: 'jpg' },
      { _id: 5c9b9662d74d5c0f766f9a16, extension: 'jpg' },
      { _id: 5c9b9667d74d5c0f766f9a17, extension: 'jpg' },
      { _id: 5c9b9670d74d5c0f766f9a18, extension: 'jpg' },
      { _id: 5c9b9679d74d5c0f766f9a19, extension: 'jpg' },
      { _id: 5c9b967ed74d5c0f766f9a1a, extension: 'jpg' },
      { _id: 5c9b9686d74d5c0f766f9a1b, extension: 'jpg' },
      { _id: 5c9b968fd74d5c0f766f9a1c, extension: 'jpg' },
      { _id: 5c9b9697d74d5c0f766f9a1d, extension: 'jpg' },
      { _id: 5c9b969ad74d5c0f766f9a1e, extension: 'jpg' },
      { _id: 5c9b96a4d74d5c0f766f9a1f, extension: 'jpg' },
      { _id: 5c9b96afd74d5c0f766f9a20, extension: 'jpg' },
      { _id: 5c9b96b5d74d5c0f766f9a21, extension: 'jpg' },
      { _id: 5c9b96bbd74d5c0f766f9a22, extension: 'jpg' },
      { _id: 5c9b96c2d74d5c0f766f9a23, extension: 'jpg' },
      { _id: 5c9b96cbd74d5c0f766f9a24, extension: 'jpg' },
      { _id: 5c9b96d7d74d5c0f766f9a25, extension: 'jpg' },
      { _id: 5c9b96dfd74d5c0f766f9a26, extension: 'jpg' },
      { _id: 5c9b96e5d74d5c0f766f9a27, extension: 'jpg' },
      { _id: 5c9b96ead74d5c0f766f9a28, extension: 'jpg' },
      { _id: 5c9b96edd74d5c0f766f9a29, extension: 'jpg' },
      { _id: 5c9b96f3d74d5c0f766f9a2a, extension: 'jpg' },
      { _id: 5c9b96f9d74d5c0f766f9a2b, extension: 'jpg' },
      { _id: 5c9b9700d74d5c0f766f9a2c, extension: 'jpg' },
      { _id: 5c9b970ad74d5c0f766f9a2d, extension: 'jpg' },
      { _id: 5c9b970ed74d5c0f766f9a2e, extension: 'jpg' },
      { _id: 5c9b9714d74d5c0f766f9a2f, extension: 'jpg' },
      { _id: 5c9b971ad74d5c0f766f9a30, extension: 'jpg' },
      { _id: 5c9b9723d74d5c0f766f9a31, extension: 'jpg' },
      { _id: 5c9b972ad74d5c0f766f9a32, extension: 'jpg' },
      { _id: 5c9b9733d74d5c0f766f9a33, extension: 'jpg' },
      { _id: 5c9b973ad74d5c0f766f9a34, extension: 'jpg' },
      { _id: 5c9b9741d74d5c0f766f9a35, extension: 'jpg' },
      { _id: 5c9b974bd74d5c0f766f9a36, extension: 'jpg' },
      { _id: 5c9b9750d74d5c0f766f9a37, extension: 'jpg' },
      { _id: 5c9b9759d74d5c0f766f9a38, extension: 'jpg' },
      { _id: 5c9b975fd74d5c0f766f9a39, extension: 'jpg' },
      { _id: 5c9b9764d74d5c0f766f9a3a, extension: 'jpg' },
      { _id: 5c9b9769d74d5c0f766f9a3b, extension: 'jpg' },
      { _id: 5c9b976ed74d5c0f766f9a3c, extension: 'jpg' },
      { _id: 5c9b9775d74d5c0f766f9a3d, extension: 'jpg' },
      { _id: 5c9b9780d74d5c0f766f9a3e, extension: 'jpg' },
      { _id: 5c9b978cd74d5c0f766f9a3f, extension: 'jpg' },
      { _id: 5c9b9796d74d5c0f766f9a40, extension: 'jpg' },
      { _id: 5c9b979ed74d5c0f766f9a41, extension: 'jpg' },
      { _id: 5c9b97a2d74d5c0f766f9a42, extension: 'jpg' },
      { _id: 5c9b97a6d74d5c0f766f9a43, extension: 'jpg' },
      { _id: 5c9b97add74d5c0f766f9a44, extension: 'jpg' },
      { _id: 5c9b97b3d74d5c0f766f9a45, extension: 'jpg' },
      { _id: 5c9b97b7d74d5c0f766f9a46, extension: 'jpg' },
      { _id: 5c9b97c0d74d5c0f766f9a47, extension: 'jpg' },
      { _id: 5c9b97cad74d5c0f766f9a48, extension: 'jpg' },
      { _id: 5c9b97d1d74d5c0f766f9a49, extension: 'jpg' },
      { _id: 5c9b97d7d74d5c0f766f9a4a, extension: 'jpg' },
      { _id: 5c9b97dcd74d5c0f766f9a4b, extension: 'jpg' },
      { _id: 5c9b97e0d74d5c0f766f9a4c, extension: 'jpg' },
      { _id: 5c9b97e6d74d5c0f766f9a4d, extension: 'jpg' },
      { _id: 5c9b97efd74d5c0f766f9a4e, extension: 'jpg' },
      { _id: 5c9b97f6d74d5c0f766f9a4f, extension: 'jpg' },
      { _id: 5c9b97fbd74d5c0f766f9a50, extension: 'jpg' },
      { _id: 5c9b9800d74d5c0f766f9a51, extension: 'jpg' },
      { _id: 5c9b9808d74d5c0f766f9a52, extension: 'jpg' },
      { _id: 5c9b9810d74d5c0f766f9a53, extension: 'jpg' },
      { _id: 5c9b9814d74d5c0f766f9a54, extension: 'jpg' },
      { _id: 5c9b9819d74d5c0f766f9a55, extension: 'jpg' },
      { _id: 5c9b981ed74d5c0f766f9a56, extension: 'jpg' },
      { _id: 5c9b9825d74d5c0f766f9a57, extension: 'jpg' },
      { _id: 5c9b9829d74d5c0f766f9a58, extension: 'jpg' },
      { _id: 5c9b982dd74d5c0f766f9a59, extension: 'jpg' },
      { _id: 5c9b9831d74d5c0f766f9a5a, extension: 'jpg' },
      { _id: 5c9b9837d74d5c0f766f9a5b, extension: 'jpg' },
      { _id: 5c9b983dd74d5c0f766f9a5c, extension: 'jpg' } ],
   highlighted: false }
```

Here is an extract of the stats after a few hours of usage (it ceases to evolve since we can only ever have a max of 14 keys):
`{ hits: 7038, misses: 14, keys: 14, ksize: 462, vsize: 6720 }`

Is it the case that the object is too big ? Are we getting expected performance ? Is there anything else we should be considering at this stage ?

Many thanks in advance !

**Comment by erdii** [comment]
Hey @vinoa-team :)

Can you please paste me the exact version number of node-cache you are using?
And your node-cache instantiation with options, too (where you call `new NodeCache(options)`?

Thank you!

**Comment by Stono** [comment]
I got to the bottom of this I believe, the `useClones=true` option _destroys_ performance, especially on larger objects.

With `useClones` (440ms):
```
  at:controllers:web getting network policies +0ms
  at:cache Kubernetes:get:"extensions",1,"networkpolicies" handling +15ms
  at:cache Kubernetes:get:"extensions",1,"networkpolicies" returning cached result +440ms
```

Without `useClones`, and instead using https://lodash.com/docs/#cloneDeep (7ms):
```
  at:controllers:web getting network policies +0ms
  at:cache Kubernetes:get:"extensions",1,"networkpolicies" handling +7ms
  at:cache Kubernetes:get:"extensions",1,"networkpolicies" returning cached result +0ms
```

Not sure on your clone implementation, but i'd switch it out for lodashes!

**Comment by vinoa-team** [comment]
Hi @erdii and @Stono - thanks a lot for the quick replies.
I can confirm that I am using  "node-cache": "^4.2.1", and also `useClones: true` which I believe is the recommended setting ?

Will try and give the `useClone: false` option a go and see what happens. Is it because the plugin is parsing the big object in some ways that it slows it down so much ? I'm not super bothered by cloning issues, since I'm storing my keys as category_<unique-mongo-id> => {object} so my keys and values should be more or less unique and I've got a system to update the cache when the categories get updated. 
So do you reckon I should go for useClone:false ?

Thanks !!
G

**Comment by Stono** [comment]
Try it... depends how good your code is and if you're honouring immutability.

**Comment by erdii** [comment]
Personally I would recommend `useClones: false` because of perfomance all the time!

The difference is, if useClones is diabled, node-cache only caches references and does not "clone" whole objects. This is a lot faster, but you also have to ensure, that you do not mutate objects after they have been cached, because you will mutate the cached object and not a copy/clone.


Thank you @Stono for benchmarking lodash's cloneDeep! I will have a look at it and compare it with our current clone dependency. (We just removed all of lodash 😭)

**Comment by vinoa-team** [comment]
Thanks ! I've had another play, and I got it down to 12ms for a get on the object, by setting `useClone:false`

Will continue to explore a few different options, as I imagine there's still something slightly wrong, and I should be getting a better result based on @Stono 's benchmark

Thanks a lot both for your help !

**Comment by erdii** [comment]
I copy-pasted @vinoa-team s data and fired up a small benchmark: https://github.com/erdii/node-cache/commit/e48b931666119eb1bae5030ba6e8a43f9180283e with both "clone-engines".

The benchmark sets the copied object in 50000 keys and measures + averages times:
* clone: { sum: 15202, avg: 0.30404 }
* lodash/deepClone: { sum: 7563, avg: 0.15126 }

This is a clear win for lodash!
Sadly, lodash does not support cloning promises for now and we have to weigh if we want to drop promise support for performance or not.

**Comment by Stono** [comment]
Why would you "store" a promise? 🤷‍♂

**Comment by erdii** [comment]
I also would strongly advise against storing complex stuff like promises, functions etc.
Especially without disabling `useClone`!

I know that there have been Issues in the past with people failing to store complex types, such as promises and functions, because the `useClone` option is enabled by default, these issues have been mostly resolved by the update to node@v2, because it now supports more types, that's why I hesitate to drop it now for lodash's implementation. Altough the performance gain speaks for itself..
