### ISSUE TITLE
What is the ETA for the 5.0.0 version?

### ISSUE THREAD

**Issue by ahmednawar** [node-cache/node-cache#148]

**Comment by erdii** [comment]
in the next few weeks. Sadly we cannot prodive an exact date because we've got much work to do and node-cache doesn't get us food on the plates :/

**Comment by erdii** [comment]
I have published a 5.0.0-alpha.0 package on npm. You can try it with: npm install node-cache@alpha

**Comment by erdii** [comment]
Wohoo node-cache@5.0.0 has landed right now! Sorry for the long wait.

**Comment by ahmednawar** [comment]
Thanks!
