### ISSUE TITLE
migration guide v4 -> v5

### ISSUE THREAD

**Issue by oprogramador** [node-cache/node-cache#153]
Could you publish a migration guide explaining how to correctly upgrade `node-cache` from v4 into v5?

At https://github.com/node-cache/node-cache/releases I see only an announcement of 5.0.0 with no info about breaking changes but I'd like to ensure.

**Comment by daluf** [comment]
You can view the breaking changes in the "Breaking changes" section as seen here: https://github.com/node-cache/node-cache#breaking-changes. Basically it still works the same, but if you do use callbacks you will need to add the `enableLegacyCallbacks` option and set it to `true`. Callbacks will be entirely removed in `6.x`.

**Comment by erdii** [comment]
@oprogramador I'm sorry to hear that. Hope @daluf could already help!
---
I see that we missed some releases on the [releases page](https://github.com/node-cache/node-cache/releases), we will add all missing releases and changelog there.

**Comment by erdii** [comment]
I added the missing releases and a migration guide for v5.x:
* https://github.com/node-cache/node-cache/releases
* https://github.com/node-cache/node-cache/releases/tag/v5.0.0
