### ISSUE TITLE
deleteOnExpire: false appears to be ignored in version 5

### ISSUE THREAD

**Issue by fielding-wilson** [node-cache/node-cache#154]
Hi,

I have defined my cache as follows:
`const cache = new NodeCache({deleteOnExpire: false})`

For testing purposes, I store a key with a ttl of 60:
`cache.set(key, data, 60)` 

In 4.2.1, I am still able to get the key after 1 minute. In 5.0.0 and 5.0.1, I get _undefined_ when trying to get the key after 1 minute.

Thanks for your help

**Comment by erdii** [comment]
I will investigate this!

**Comment by erdii** [comment]
@daluf removed the behavior in dcb3a19ec7459ee08b4df9f24dfb047a389dd989.
I remember that we briefly talked about this, do you still know what we talked?
In hindsight, this could have been the wrong move :/

**Comment by erdii** [comment]
I have release a fixed version: https://github.com/node-cache/node-cache/releases/tag/v5.0.2
I'm sorry for the long delay, though :(
