### ISSUE TITLE
safe defaults to prevent memory fault

### ISSUE THREAD

**Issue by bradoyler** [node-cache/node-cache#155]
So it looks like the default `stdTTL` and `maxKeys` are both set to "unlimited". 
Wouldn't this cause memory problems for those that don't "read the docs" or forget to set these values?
I'd like to propose setting these defaults to `{ stdTTL: 3600, maxKeys: 1000000 }`, unless there's another way to handle perceived memory leak when not setting these values.

🍻

**Comment by erdii** [comment]
Hey @bradoyler, welcome here! :)
This sounds reasonable for me; I'll reiterate with the team and see what we can do.

Only cons I see (for now):
* Backwards compatibility (e.g. old setup that uses more keys that our maxKeys default)

**Comment by jtsmedley** [comment]
Instead of changing backwards behavior you could add an invalidate policy like Redis
