### ISSUE TITLE
High CPU consumption when using high values for stdTTL and checkperiod

### ISSUE THREAD

**Issue by andyschr** [node-cache/node-cache#157]
When using the module with high values for ttl and checkperiod the cpu consumption increases a lot.

I use the module as follows:
const day = 1000 * 60 * 60 * 24; // day in ms
const mtImageCache = new NodeCache({ stdTTL: day*5, checkperiod: day, useClones : false });

After using lower values like 
const mtImageCache = new NodeCache({ stdTTL: 1000000, checkperiod: 1000000, useClones : false });

the consumption comes back to a normal level.

Version: 5.0.2
Node: 8.x

**Comment by erdii** [comment]
Hey @andyschr, welcome here!
I'm sorry to hear that and will investigate!!

Is the cpu usage thing immediately noticeable?

**Comment by erdii** [comment]
Wait. I just reread the issue and noticed that you use milliseconds instead of seconds!

When i try to run this code:

```javascript
 const Cache = require("node-cache");

const c = new Cache({
	stdTTL: 1000 * 60 * 60 * 24 * 5, // 5 days in milliseconds
	checkperiod: 1000 * 60 * 60 * 24 * 1, // 1 day in milliseconds
	useClones: false,
});
```
I get:
```
node test.js
(node:32737) TimeoutOverflowWarning: 86400000000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:32737) TimeoutOverflowWarning: 86400000000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```


is this your problem?
