### ISSUE TITLE
Flush stats

### ISSUE THREAD

**Issue by melissafzhang** [node-cache/node-cache#158]
Is there a way to flush stats? I would like to see how many cache hits/misses there are in a given time period. Thanks!

**Comment by sujeshthekkepatt** [comment]
You can use `myCache.getStats()` for getting info on cache. To flush all data you can use `myCache.flushAll()`.

**Comment by melissafzhang** [comment]
I’m looking to flush just the stats and not the entire cache. This is useful for sending metrics to a data pipeline.

**Comment by sujeshthekkepatt** [comment]
I think there is no method for just flushing stats.

**Comment by erdii** [comment]
@melissafzhang hey and welcome here :)

Do I understand this correctly:
You'd need a new function `cache.flushStats()` that resets the stats back to 0?

We do not expose such a function for now, but you can (for the time being) use this hack:

```javascript
cache.stats = {
	hits: 0,
	misses: 0,
	keys: 0,
	ksize: 0,
	vsize: 0,
}
```

**Comment by sujeshthekkepatt** [comment]
@erdii are you working on this? If not I can take it upon.

**Comment by erdii** [comment]
@sujeshthekkepatt that would be nice!  :)

**Comment by sujeshthekkepatt** [comment]
Cool. I will work on it. :). Please do assign me on the issue :)

**Comment by erdii** [comment]
#161 has landed! thanks to @sujeshthekkepatt for the implementation and @melissafzhang for the idea
