### ISSUE TITLE
How to get multiple previous values,

### ISSUE THREAD

**Issue by sankar9659** [node-cache/node-cache#162]
I have added a chat screen in my app, In that, I have used socket server to send and receive messages,
I want to store the entire chat history on the server-side, so I chose node cache package, If I get values, using MGET it gives only the last message, please give me an example to store and retrieve the entire messages, using this package.
this is my code

function storeMultipleKeys(data, res) {
	console.log('dataFunc', data);
	const success = myCache.mset([{ key: 'customer', val: data }, { key: 'store', val: data }]);
	console.log('success', success);
	const value = myCache.mget(['customer', 'store']);
	let array = [];
	if (value == undefined) {
		console.log('valueIF', value);
	} else {
		console.log('valueELSE', value);
		array = [...array, { ...value }];
		console.log('array', array);
	}
}

**Comment by erdii** [comment]
mset/mget are working on my machine:

```
> let Cache = require("node-cache")
undefined
> let c = new Cache()
undefined
> c.mset([{key: "hi", val: "ho"}, {key: "foo", val: "bar"}])
true
> c.data
{ hi: { t: 0, v: 'ho' }, foo: { t: 0, v: 'bar' } }
> c.mget(["hi", "foo"])
{ hi: 'ho', foo: 'bar' }
>
```

---

I think that you have a wrong notion of what .mset() does.
It does: set/override multiple keys at once
It does not: append data to a key that was already set.

---

```javascript 
const Cache = require("node-cache")

// we disable `useClones` to speed up caching of huge history arrays
const historyCache = new Cache({ useClones: false });

function appendMessage(message) {
  // get existing history or default to empty array
  const history = historyCache.get("history-for-user-X") || [];

  // add message to history
  history.push(message);

  historyCache.set("history-for-user-X", history);
}
```
