### ISSUE TITLE
Force expire when cache is full

### ISSUE THREAD

**Issue by xogeny** [node-cache/node-cache#164]
Sorry if this is a repeat, but I didn't see it mentioned anywhere.  I think it would be useful to have an option to force expire the oldest entry if the cache is full.  I'd suggest first running `._checkData()` manually to see if you can lose some keys via TTL attrition.  If not (and the `forceExpire` option is `true`), then run `.delete(keys()[0])`.  This is a cache after all, I personally don't have any issue if the cache makes space for newer items.

BTW, I tested it and `.keys()` is in chronological order.  I suspect this can be proven from Javascript semantics, but it is certainly empirically true.  I'd gladly submit a PR for this if this functionality is approved (never used CoffeeScript, but I suspect I could manage it...much better in TypeScript 😉 ).

**Comment by erdii** [comment]
Hey @xogeny welcome here :)

We already stated that an LRU/LFU cache is out of scope for this project as the complexity of doing that "right" would be too big. I think we should compile a list of frequently asked questions to give these questions and their answers more visibility as it's very hard to search for all possible phrasings of a question.

> BTW, I tested it and .keys() is in chronological order

Don't rely on this! I have yet to encounter a js engine that does not order the keys like that, but the JS spec explicitly states that key ordering is not guaranteed at all.

Someone else already summarised that better than I could: https://stackoverflow.com/a/5525820

**Comment by adevine** [comment]
One other note about this comment:

>
>> BTW, I tested it and .keys() is in chronological order
>
>Don't rely on this! I have yet to encounter a js engine that does not order the keys like that, but the JS spec explicitly states that key ordering is not guaranteed at all.

That's not true for ES2015 and later, the spec **does** guarantee that objects return keys in insertion order, so if people are using this library on a recent JS implementation they can depend on that. See the "Key Order" note here, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map :

> Note: Since ECMAScript 2015, objects do preserve creation order for string and Symbol keys. In JavaScript engines that comply with the ECMEScript 2015 spec, iterating over an object with only string keys will yield the keys in order of insertion.

**Comment by erdii** [comment]
you are right! further discussion in #166
