### ISSUE TITLE
Add method to get keys ordered by time to expire

### ISSUE THREAD

**Issue by adevine** [node-cache/node-cache#166]
First wanted to comment that I *did* see that you just closed this issue yesterday, https://github.com/node-cache/node-cache/issues/164 , regarding not wanting to implement full LRU cache semantics, and I fully understand that. That said, the current semantics around maxKeys is extremely limiting: either I have a fully unbounded cache with maxKeys = -1, or if the cache is full I don't really have any reasonable (performant) way to determine which keys I should remove.

Thus, I propose adding a method that gets keys in order of the nearest time-to-expire, with a limit on the number of keys returned, e.g. `keysByExpiration(maxNumKeys)` (maxNumKeys would be optional, if not set all keys are returned). Without implementing full LRU semantics, it at least allows me to manually expire a key when the cache is full (or better yet, could make that an option regarding how maxKeys is interpreted).

In addition, a data structure of keys ordered by expiration time would also make the implementation of _checkData much more performant. Right now that method needs to look at ALL the entries in the cache, instead of just the ones that are post-expiration time.

Just wanted to see if you'd be willing to take a PR that implemented this. This is critical functionality for me so I'll need to fork in any case, but would like to push this PR back upstream if you're willing to take it.

**Comment by erdii** [comment]
hey @adevine :) welcome!

> That said, the current semantics around maxKeys is extremely limiting: either I have a fully unbounded cache with maxKeys = -1, or if the cache is full I don't really have any reasonable (performant) way to determine which keys I should remove.

you are right

> Thus, I propose adding a method that gets keys in order of the nearest time-to-expire, with a limit on the number of keys returned, e.g. keysByExpiration(maxNumKeys)

nice idea in tandem with:

> In addition, a data structure of keys ordered by expiration time would also make the implementation of _checkData much more performant. 

which would also be very nice!
I'd be willing to take a pr or we could try to draft an approach together.
What do you have in mind?

**Comment by adevine** [comment]
Thanks very much @erdii . My recommendation would be to do this:

1. You'll need a priority queue to order the keys by their expiration time. Here is an example of a small, simple, fast priority queue: https://github.com/mourner/flatqueue . I'm not necessarily suggesting adding that as a dependency as-is, but as you can see from the implementation it's really small, the whole class is only 80 lines. Given the standard patterns of using a cache (i.e. my guess is 95%+ of the time the item `set` first is the oldest) might be able to get better performance with some modifications to a generic priority queue (i.e. always checking first if the new item you're adding has the lowest priority, because again it most cases it will).
2. Whenever you add, delete or update the TTL of a key, you need to run the appropriate push/pop methods on the priority queue.

May consider making this functionality optional, it will add some overhead.

**Comment by musicin3d** [comment]
+1 to this. I actually expected the oldest item in the cache to be removed when the limit was exceeded. Adding some means of finding the the oldest items would at least enable manual memory management.

**Comment by musicin3d** [comment]
Well, I still want it. I'll see if I can find some time to implement this based on the discussion.

**Comment by erdii** [comment]
sorry for not reacting in time!

I don't think that this is acceptable behavior as we either implement the queue "correct" or not. Maybe you should have a look at: https://www.npmjs.com/package/lru-cache

**Comment by erdii** [comment]
WDYT about exposing a handler, like @adevine proposed in the initial comment, that gets called before an error would be thrown when the cache is full?

This way, the user could take care of expiring unwanted keys themselves.
But they would also have to set the key manually inside.

Something like:

```javascript
const cache = new NodeCache({
  maxKeys; 1000,
  handleCacheOverflow: (cache, key, value) => {
    if (Math.random() > 0.7) {
      return undefined; // tell node-cache that we didn't handle the overflow and an error should still be thrown
    }

    // make room for new key and set it afterwards
    cache.del("myKey");
    cache.set(key, value);

    return true; // tell node-cache that we handled the overflow and no error should be thrown
  },
})
```
