### ISSUE TITLE
Key prefix

### ISSUE THREAD

**Issue by mehdikhody** [node-cache/node-cache#170]
Hi, I'm working on a project and I wonder is there any way to add prefix for key? 
like this:
```js
import NodeCache from "node-cache";

const cache = new NodeCache({ prefix: "fookey-" });
cache.set("name", "Foo"); // sets fookey-name
cache.get("name"); // fookey-name = Foo
// or
cache.prefix = "barkey-";
cache.get("name"); // barkey-name = undefined
```

**Comment by erdii** [comment]
hey @mehdikhody sorry for not answering for a long time.

I honestly do not see the use case in this.
What do we gain from setting a "cache-wide" key prefix?
