### ISSUE TITLE
Using jest fakeTimers results in a null pointer exception

### ISSUE THREAD

**Issue by mikefarah** [node-cache/node-cache#172]
When using jest.fakeTimers, it (seems) to mock out setTimeout to return undefined.

This then causes an issue with node-cache when it attempts to see if the result has 'unref' defined:

https://github.com/node-cache/node-cache/blob/fd1a54f10b7f954e89e99e2c981ec76128f675ac/_src/lib/node_cache.coffee#L483

**Comment by taylorjdawson** [comment]
@mikefarah were you successful in using `jest.fakeTimers` with node-cache? So far using fake timers my node-cache doesn't actually expire
