### ISSUE TITLE
how node-cache behave in AWS Lambda runtime?

### ISSUE THREAD

**Issue by Ali-Dalal** [node-cache/node-cache#173]
just got a curious question, will node-cache work in AWS lambda runtime?

I am doing a case study where the maximum number of concurrent lambdas at a time will be 10. 

each lambda container might stay alive up to 20 minutes so in this case I want to fetch some of the data from the cache. not asking the DB again for the same data.

is this possible?

NOTE: I haven't tried it yet on AWS lambda but just asking first.

Thanks.

**Comment by sujeshthekkepatt** [comment]
node-cache is an in-memory caching lib. So you can use it as long as was lambda function alive.

**Comment by Ali-Dalal** [comment]
I tried it and it works as expected.
Thanks

**Comment by pomSense** [comment]
A note here is the lambda cache will be in tact as long as the lambda's current execution context is valid. When AWS Lambda executes your function on your behalf, it first creates an execution context, which is a temporary runtime environment that initializes any external dependencies of your lambda function. This execution context is reused for subsequent function invocations if they are close together, which allows data to be cached in memory or connections to be kept alive (like database connections), for future invocations.

In this scenario, it will work.

If your executions are farther apart, and lambda destroys the previous execution context, in that case the cache will also be destroyed.

An easier way to look at it is while the function is 'warm', the caching will work. When it goes 'cold', the cache is destroyed. 

This will work well (and caching should always be done) if you have a lambda that is getting a TON of requests /min.
