### ISSUE TITLE
Wait until key exists

### ISSUE THREAD

**Issue by jadbox** [node-cache/node-cache#174]
It would be great to have a promise that blocks until a specific key is set.

**Comment by sujeshthekkepatt** [comment]
@jadbox I think a typescript port is on work.

**Comment by erdii** [comment]
We strictly removed all async api's from node-cache to keep the scope and complexity of this module simple and small.

May I propose this snippet:

```javascript
function sleep(milliseconds) {
  return new Promise((resolve) => setTimeout(resolve, milliseconds));
}

async waitForKey(cache, key) {
  while (true) {
    if (cache.has(key) {
      break;
    }
    await sleep(1000);
  }
}
```

PS: @sujeshthekkepatt idk if the typescript port will happen anytime soon due to missing time on my side. :/
