### ISSUE TITLE
checkperiod naming convention inconsistency

### ISSUE THREAD

**Issue by Qix-** [node-cache/node-cache#177]
Minor nit-pick, but is there a reason `checkperiod` isn't `checkPeriod`? All of the other options are camelCased.

Just a small thing I noticed 🙃  I really appreciate the exceptional quality of this module, so thank you for that.

**Comment by erdii** [comment]
heh! good catch! :D
the api is riddled with some inconsistencies and we did not change them to avoid breaking existing users. There are currently no plans to work this out but maybe we can have a planned chain of some releases were we first introduce an *additional* setting `checkPeriod`, log a warning when someone uses `checkperiod` and that we will remove it in the next major release.
