### ISSUE TITLE
not firing - ... myCache.on( "expired", function( key, value ) ... 

### ISSUE THREAD

**Issue by Dorian-Grim** [node-cache/node-cache#178]
Imo I am doing a very simple, script:

```javascript
let id = 245637356,
    username = 'myUser',
    discriminator = '1234',
    userCacheObject = myCache.get(id),
    sessionMaxTime = 2;

    if (myCache.get(id) == undefined) // first run
    {
        let obj = { id: id, username: username , discriminator: discriminator};
        myCache.set( id, obj, sessionMaxTime);
    }
    else myCache.ttl(id, sessionMaxTime); // refresh current ttl

    myCache.on( "expired", function( key, value )
    {
        console.log(key, value); // event never fires
    });
```
The event for key expiry never fires. What am I missing?

**Comment by sujeshthekkepatt** [comment]
Can you elaborate more on the issue? Seems it works fine. On a quick glance, If the frequency of the cache access < 2 seconds your cache will not expire since every cache hit results in overwriting the `ttl`.

**Comment by Dorian-Grim** [comment]
> Can you elaborate more on the issue? Seems it works fine. On a quick glance, If the frequency of the cache access < 2 seconds your cache will not expire since every cache hit results in overwriting the `ttl`.

After two seconds pass, the `expired` callback doesn't log to console... I also tried with 10 seconds.

**Comment by sujeshthekkepatt** [comment]
Can you provide full code on the logic? The above one works fine @Dorian-Grim

**Comment by georgeglessner** [comment]
I just started using this module today. @Dorian-Grim are you expecting the event to fire automatically? That's what I thought it did at first, but realized you must call the file it is on in order for it to fire. So if your implementation is on `index.js` you would have to hit `index.js` in order for the event to fire.

**Comment by Dorian-Grim** [comment]
> Can you provide full code on the logic? The above one works fine @Dorian-Grim
**https-proxy.js**
```javascript
if (!process.env.http_proxy) return;

var url    = require('url');
var tunnel = require('tunnel');
var proxy = url.parse(process.env.http_proxy);

var tunnelingAgent = tunnel.httpsOverHttp({
  proxy: {
    host: proxy.hostname,
    port: proxy.port
  }
});

var https = require('https');
var oldhttpsreq = https.request;
https.request = function (options, callback) {
  options.agent = tunnelingAgent;
  return oldhttpsreq.call(null, options, callback);
};

var http = require('http');
var oldhttpreq = http.request;
http.request = function (options, callback) {
  options.agent = tunnelingAgent;
  return oldhttpreq.call(null, options, callback);
};
```
**test.js**
```javascript
require(`https-proxy`); // I am behind a corporate firewall
const NodeCache = require( "node-cache" );
const myCache = new NodeCache();
const { Client, MessageAttachment } = require(`discord.js`);
const id = 245637356,
username = `myUser`,
discriminator = `1234`,
sessionMaxTime = 10;
const client = new Client();

client.on(`message`, async message => 
{
    if(message.author.bot) return;
    if(message.channel.name) return;
    if (message.channel.type == 'dm')
    {
		if (myCache.get(id) == undefined) // first run
		{
			let obj = { id: id, username: username , discriminator: discriminator};
			myCache.set( id, obj, sessionMaxTime);
			console.log('cache set');
		}
	};
});
myCache.on( "expired", function( key, value )
{
	console.log(key, value); // event never fires
});
client.login(`myToken`);
```

**Comment by Dorian-Grim** [comment]
> I just started using this module today. @Dorian-Grim are you expecting the event to fire automatically? That's what I thought it did at first, but realized you must call the file it is on in order for it to fire. So if your implementation is on `index.js` you would have to hit `index.js` in order for the event to fire.

Ok, I admit, I am dumb :) :

the ... `.emit("expired"` ... is done inside `_check` which is called in `_checkData`, the line with `this.checkTimeout = setTimeout(this._checkData, this.options.checkperiod * 1000, startPeriod);` which is only happening if `startPeriod` is true and `checkperiod` from options is larger than 0.

So to answer your unplaced question @georgeglessner and my asked one, do this for you to be able to not "_call the file_". It will automatically trigger.

```javascript
const myCache = new NodeCache({ checkperiod: 1 });
```

Problemo solved, there's no issue here...
