### ISSUE TITLE
Extra mode, expire key update instead of delete key

### ISSUE THREAD

**Issue by hua1995116** [node-cache/node-cache#179]
When my cache expires, I expect to update the cache instead of deleting it. I hope to have an option when initializing, whether to delete the key or update the key when it expires, when updating the project, you can fill in a custom function to update the corresponding key.

```javascript
const myCache = new NodeCache( { stdTTL: 60, checkperiod: 0, mode: 'update', updateAction: (key, oldValue) => { 
   // some code
   return newValue;
} } );
```

**Comment by sujeshthekkepatt** [comment]
To do this currently, you have to do a workaround like setting again the key when it expires by using expired events.  Also, you can choose to make `deleteOnExpire: false` (which is not so flexible). But it's fairly easy to implement your own logic with events. What do you think @hua1995116 @erdii

**Comment by hua1995116** [comment]
Because my key update process is time-consuming (I will request a remote url to get the result), so I do n’t want to delete the original cache directly. `deleteOnExpire: false` and `expired events` together can really achieve my current situation. Thank you@sujeshthekkepatt

**Comment by erdii** [comment]
@hua1995116 hey and welcome :) I don't think that we should add automatic refresh functionality for "always-hot"-ish caches. As @sujeshthekkepatt pointed out. this can already be achieved with a little bit of glue code on your side. Are you ok with this approach?

PS: @sujeshthekkepatt thanks for dropping by from time to time! I appreciate that!

**Comment by hua1995116** [comment]
I think it's ok. @erdii
