### ISSUE TITLE
Different ttl for nested object.

### ISSUE THREAD

**Issue by wgomg** [node-cache/node-cache#182]
Read this https://github.com/node-cache/node-cache/issues/77 but asking for confirmation. Is there any way to set different ttl in a nested object? 

For example, something like this:
```javascript
nodeCacheKey: {
  nestedKey1: {...} // ttl 5 hours
  nestedKey2: {...} // ttl 24 hours
}
```
As i understand, currently ttl is setted for the entire value/object setted on `nodeCacheKey`.

**Comment by erdii** [comment]
No this is not supported but you can break up your cached object into multiple portions with differerent ttl:

```javascript
const cache = new NodeCache();

const myComplexObject = {
  nestedKey1: {
    foo: "bar",
  },
  nestedKey2: {
    answer: 42,
  },
};

cache.set("myComplexObject.nestedKey1", myComplexObject.nestedKey1, 600);
cache.set("myComplexObject.nestedKey2", myComplexObject.nestedKey2, 300);
```
