### ISSUE TITLE
Feature idea: LRU cache 

### ISSUE THREAD

**Issue by AdityaAnand1** [node-cache/node-cache#193]
In addition to letting the user specify custom cache expiration configuration, how about an LRU cache? (LRU = Least recently used)

You just specify the maximum size of the cache in bytes and that's it. What is kept in the cache or not is decided automatically, based on access frequency. What is used more, remains in cache longer.

Since anyone would always want frequently accessed static cache values to ALWAYS be in cache, LRU is meant for just such use cases.

Plus, it can go along with TTL as well. As in, keep the most used values in cache, but still update them from time to time.

**Comment by erdii** [comment]
Hey @AdityaAnand1! :)

For now, there are no plans to implement LRU functionality.
Please use lru-cache: https://www.npmjs.com/package/lru-cache
