### ISSUE TITLE
Misleading error message 

### ISSUE THREAD

**Issue by shhadi** [node-cache/node-cache#194]
The message "Cache max key size exceeded" is misleading and indicates that the size of the key length is exceeded,  In fact should be: "Cache max keys amount exceeded"

**Comment by shhadi** [comment]
I've tried to open a PR of this simple change but it seems there is a permissions restrictions on who can push changes to branches.

**Comment by erdii** [comment]
Hey @shhadi welcome! :)

>  In fact should be: "Cache max keys amount exceeded"

agreed!

> I've tried to open a PR of this simple change but it seems there is a permissions restrictions on who can push changes to branches.

Huh! I'd happily accept a PR on that and also some screenshots of your PR rights issue, so I can fix it.
