### ISSUE TITLE
Does this storage is isolated per every request?

### ISSUE THREAD

**Issue by sayjeyhi** [node-cache/node-cache#201]
Hi threre 
thanks to good job on this,

I want to know, if we have 300 concurrent user which are working with app, the cache values are isolated for each user?

**Comment by erdii** [comment]
that depends on your code and the architecture of your app.

new cache on every request (ikr, this does propably not make sense :sweat_smile:):
```
app.get("/", (req, res, next) => {
  const cache = new NodeCache();
  cache.set("hi", Math.random());
  res.send(cache.get("hi"));
})
```


static cache on shared between requests:
```
const cache = new NodeCache();

app.get("/", (req, res, next) => {
  if (!cache.has("hi") {
    cache.set("hi", Math.random());
    res.send("cache miss");
    return;
  }

  res.send(`cache hit: ${cache.get("hi")}`);
})
```
