### ISSUE TITLE
Take does not delete

### ISSUE THREAD

**Issue by sacredwx** [node-cache/node-cache#203]
Take does not delete the object when the object is null.

`
> cache.set('test');
true
> cache.has('test')
true
> cache.take('test')
null
> cache.has('test')
true
> cache.take('test')
null
> cache.take('test')
null
`

**Comment by erdii** [comment]
Thanks for reporting!

We should propably replace [this check](https://github.com/node-cache/node-cache/blob/master/_src/lib/node_cache.coffee#L306) (and, for consistency, all other existence checks) with a call to `this.has`.

**Comment by erdii** [comment]
@sacredwx since you already did the fix: can you please create a pr with it here?

**Comment by sacredwx** [comment]
@erdii , I did not fix it, sorry, actually what I did before was a creation of take function wrapper that does .get and then .del
