### ISSUE TITLE
Find/delete cache key by a pattern

### ISSUE THREAD

**Issue by hsynlms** [node-cache/node-cache#211]
I just wonder if it's possible to find/delete a cache key by a given pattern may be a regex, glob? This can be helpful when `node-cache` package is used in a web project which caches the response by using some request parameters as the cache key to making the cached data unique for each request.

**Comment by erdii** [comment]
Hey @hsynlms :)

It would be possible by iterating over the cache's current keys and filtering them via regex/glob but this is not currently part of node-cache. 

I'll leave this issue open so we can think about adding it as a feature. (This is no promise, though)

**Comment by hsynlms** [comment]
Sure, no promise :)

**Comment by sujeshthekkepatt** [comment]
This is interesting. It will be a cool feature. But implementations need care since regexes are always an attack vector. If this is going to implement, how does the regex/glob matching would take place? I mean should we delegate it to another package or on our own @erdii ?
