### ISSUE TITLE
Unhandled Exception Thrown When Cache Folder Contains a Directory

### ISSUE THREAD

**Issue by jerrens** [node-cache/node-cache#222]
I had created a cache directory in a subfolder (.cache/folder1/folder2) and later realized that I didn't need that deep of a hierarchy, so I changed the code to just use .cache/folder1.  This left the artifact of the sub directory 'folder2' inside of folder1, but it was empty and no longer referenced.  However, I started to get the following random errors in the code:

```
(node:11855) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
(node:11855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
```

After a little investigation, I removed that folder2 subdirectory and the problem has disappeared.

I have not dug through the code of this module, but I suspect the area of code that is performing the TTL cleanup on cache entries is not handling invalid types (directories) and is assuming that only valid cache documents would be encountered.

**Comment by sujeshthekkepatt** [comment]
A little bit more info would be useful. Sample Code may be?

**Comment by jerrens** [comment]
```
const NodePersist = require('node-persist');

process.on('unhandledRejection', (err, p) => {
    console.log('Unhandled Rejection: %s', err.message);
    if (p) {
        p.catch((pErr) => console.log(`Promise Exception: ${pErr}`));
    }
    console.log(err.stack);
});


const cacheOptions = {
	dir: path.normalize('./.cache/folder1'),
	ttl: 86400 * 1000, // one day
	expiredInterval: 1*60*1000 // cleanup expired cache every minute
};
const myCache = NodePersist.create(cacheOptions);
myCache.init();
```



If .cache/folder1 only contains files, then things work as expected.  However, if a subfolder is created inside folder1 (./.cache/folder1/folder2), then during the clean up phase (expiredInterval), the unhandledRejection is triggered.

Console Output:
```
Unhandled Rejection: EISDIR: illegal operation on a directory, read
Promise Exception: Error: EISDIR: illegal operation on a directory, read
```

Also, if there is another file in the cache location (echo 'Hello World > ./.cache/folder1/file) that was not created by node-persist, then an unhandled exception is also triggered.

Console Output: 
```
Unhandled Rejection: [node-persist][readFile] C:\Projects\BlackFishDashboard_Review\back\.cache\KernelRegression\New Text Document does not look like a valid storage file!
Promise Exception: Error: [node-persist][readFile] C:\Projects\BlackFishDashboard_Review\back\.cache\KernelRegression\New Text Document does not look like a valid storage file!
```

I think that both folders and invalid storage files should always be skipped and ignored respectively.

**Comment by sujeshthekkepatt** [comment]
@jerrens thanks for the detailed information. But i am afraid you are referring to some other cache library. Are you sure you are on the right one? Seems like you are referring the following one https://github.com/simonlast/node-persist#readme

**Comment by jerrens** [comment]
Well that isn't embarrassing at all!

So sorry about that.  I'm using node-cache in another project and completely mixed them up.
