### ISSUE TITLE
Any way to send response to an api on flush event function complete

### ISSUE THREAD

**Issue by sudhiryadav** [node-cache/node-cache#258]
I am trying to refresh cache from an api like the below method:

```javascript
function refreshCache(req, res, next) {
    appCache.flushAll();
    res.status(200).send('Cache cleared');
}
```

The flush event below is called; however I would like to send the response after the tasks are done but no way to find the response object here:

```javascript
appCache.on("flush", function () {
    reloadCache(); // <-- This is some promise and i want to send response after that.
    log.console.info('App Cache: flushed. Going to reload cache');
});
```

**Comment by danielbom** [comment]
You can use events to handle this internally on your app (not really needed) and probably an HTTP socket implementation to do that with your client.

**Comment by sudhiryadav** [comment]
@danielbom yes, that's one way to deal with it which is why I would call them as a workaround. Events, in this case, won't be reliable while the socket-based implementation would be overhead.

**Comment by danielbom** [comment]
But the implementation of `flushAll` seems synced. Then you can assume that before you call this method, your cache will be empty at the same time. The `cache.on('flush', callback) ` seems to be used in other contexts.

**Comment by sudhiryadav** [comment]
refreshCache could also fail and hence the need arise to send back the exact message to the client.  https://github.com/node-cache/node-cache/pull/260 check this out this is already implemented what i am saying. 

usecase :

```javascript
function refreshCache(req, res, next) {
    appCache.flushAll(true, req);
    res.status(200).send('Cache cleared');
}
```

```javascript
appCache.on("flush", function (res) {
    log.console.info('App Cache: flushed. Going to reload cache');
    reloadCache().then(val=>{
        if(val){
            log.console.info('App Cache: Cache reloaded');
            res.status(200).send('Cache reloaded');
        }
    }).catch(err=>{
        res.status(500).send("error");
    });
});
```

**Comment by danielbom** [comment]
#260 This not seems good use case. But, if you want this with all force, I can show an example of an EventEmitter of node to do that. Tomorrow, I build some sample to you.

**Comment by sudhiryadav** [comment]
This is my use case. I would be glad to look at your solution.

**Comment by danielbom** [comment]
const NodeCache = require("node-cache");
const { EventEmitter } = require("stream");

const ONE_SECOND = 1000;
const cache = new NodeCache();

const cacheEventEmitter = new EventEmitter();

async function reloadCache() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (Math.random() > 0.5) {
        resolve();
      } else {
        reject();
      }
    }, Math.random() * 1500);
  });
}

cache.on("flush", () => {
  reloadCache()
    .then(() => {
      cacheEventEmitter.emit("flushed");
    })
    .catch((err) => {
      cacheEventEmitter.emit("flush-fail");
    });
});

function refreshCache(req, res, next) {
  let timeoutExceeded = false;
  let resolved = false;

  cacheEventEmitter.once("flushed", () => {
    if (!timeoutExceeded) {
      resolved = true;
      res.status(200).send("Cache reloaded");
    }
  });
  cacheEventEmitter.once("flush-fail", () => {
    if (!timeoutExceeded) {
      resolved = true;
      res.status(500).send("error");
    }
  });

  setTimeout(() => {
    if (!resolved) {
      timeoutExceeded = true;
      res.status(400).send("Cache timeout");
    }
  }, ONE_SECOND);

  cache.flushAll();
}

const mockResponse = {
  status() {
    return this;
  },
  send(data) {
    console.log(data);
  },
};

refreshCache({}, mockResponse, () => {});

**Comment by danielbom** [comment]
This answer works for other things too. Your use case does an async task on the flushed data, which is not a common usage of this library. Merge your needs on `express` + `node-cache` not want to be they will accept your required changes. But you can solve your requirements in other ways, like using an EventEmmiter. I hope I can help with your needs.

**Comment by sudhiryadav** [comment]
@danielbom thanks for sharing your thoughts. Indeed it can be achieved using what code sample that you shared. I really appreciate that. I couldn't though of identifying how the event emitters keeps the objects while inside the same function scope. I have created a code sandbox extending your code if anyone can make use of the same.

https://codesandbox.io/s/node-cache-with-event-emitter-ljsdc.
