### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by gaby** [node-cache/node-cache#267]
What is the status of this project? Are you guys still maintaining it, or looking for someone to take over? 

The same question applies regarding `wg-dashboard`. I have tried contacting you all several times via different methods and no one answers their messages.

@erdii @vtii @daluf

**Comment by gaby** [comment]
Friendly bump! @erdii @vtii @daluf

**Comment by daluf** [comment]
Hey, thanks for your interest in our projects!

Currently, we are not looking for someone to take over our projects (wg-dashboard or node-cache). If you are still interested in contributing, feel free to open a pull request!

**Comment by gaby** [comment]
> Hey, thanks for your interest in our projects!
> 
> Currently, we are not looking for someone to take over our projects (wg-dashboard or node-cache). If you are still interested in contributing, feel free to open a pull request!

Hello @daluf 

The readme for `wg-dashboard` says to contact you guys if interested in the project. The project was archived last year so no one can create issues/PRs. 

https://github.com/wg-dashboard/wg-dashboard

![Screenshot_20211103-081043](https://user-images.githubusercontent.com/835733/140057742-a53eaa74-0ff0-4f00-8924-5a00c45b9b32.png)
![Screenshot_20211103-081029](https://user-images.githubusercontent.com/835733/140057746-cf1d7f6c-53e5-4c06-97b4-c3e692355584.png)

**Comment by gaby** [comment]
> Hey, thanks for your interest in our projects!
> 
> Currently, we are not looking for someone to take over our projects (wg-dashboard or node-cache). If you are still interested in contributing, feel free to open a pull request!

@daluf Regarding `node-cache`, no one seems to be looking at the PR's currently open, There hasn't been any updates in over 7 months.

**Comment by gaby** [comment]
@erdii Any updates on this?
