### ISSUE TITLE
max-memory options

### ISSUE THREAD

**Issue by guileen** [node-cache/node-cache#3]
If there is an max-memory options will be very cool.

**Comment by bojand** [comment]
I think this is a somewhat valid option to have... At least in the form of maximum # of items in the cache, default being infinite. The implementation could easily be done using least recently used key algorithm, using for example [lru-queue](https://www.npmjs.com/package/lru-queue), and just add code to `set`, `del` and `flushAll`. Would a pull request for this be accepted at all? Changes go in CoffeeScript or Javascript source code or both?
