### ISSUE TITLE
Event on Cache eviction

### ISSUE THREAD

**Issue by GeeWee** [node-cache/node-cache#317]
Hi.

I'd love to use this, in particular for caching database connections / Prisma Clients. I have a setup on AWS where I can only reuse  a prisma client for 15 minutes due to some authentication stuff.

I'd love to store it in something like `node-cache` and get the refresh in the background. The problem is that when evicting the old value from the cache, I'd need to call `prismaClient.$disconnect`

Is there any way to accomplish this, any `onEvict` event I can subscribe to with a special function or similar?

**Comment by sujeshthekkepatt** [comment]
Nodecache emits events on expiration. So you could hook something in that callback

**Comment by GeeWee** [comment]
Oh I'm super sorry, I absolutely filed this issue in the wrong repository :{
