### ISSUE TITLE
TS Errors for .d.ts file of the package

### ISSUE THREAD

**Issue by loeiks** [node-cache/node-cache#318]
When I run `tsc` locally for my project I see errors for the .d.ts file of this package here is the screenshot:

![image](https://github.com/node-cache/node-cache/assets/90484193/de600696-abb1-4043-9805-ff76d9d537c2)

I can fix it by adding `"skipLibCheck": true` to tsconfig.json but just let you guys know.

**Comment by jaredwray** [comment]
@loeiks this project hasn't had any updates for a bit. You might want to try the port I created [@cacheable/node-cache](https://www.npmjs.com/package/@cacheable/node-cache)

**Comment by loeiks** [comment]
@jaredwray thanks for the update I'll switch to that package in all of my repos/projects
