### ISSUE TITLE
Expires after no-use question

### ISSUE THREAD

**Issue by hecktarzuli** [node-cache/node-cache#85]
Any plans on creating a feature where an item expires after nobody has asked for it for X seconds (with max life of Y)?  This would ensure the most used keys stay in memory as long as possible vs a hard cut-off.

**Comment by mpneuried** [comment]
This would be a nice feature.
We will check this for future updates.

**Comment by Sivli-Embir** [comment]
👍 Is there any moment on this?

**Comment by erdii** [comment]
Currently a "Least-Recently-Used" Implementation is out of project scope :(
